import numpy, random
import matplotlib.pyplot as plt

def parta():
    r=numpy.random.random(10000)
    xmax=1
    x=numpy.sqrt(r*(xmax**2))
    plt.xlabel("Number")
    plt.ylabel("Frequency")
    plt.title("Random numbers generated by a CDF transformation method")
    plt.hist(x,bins=30,color='orange')
    plt.savefig('question 5a')
    plt.show()
parta()

def pdf(x):
    xmax=1
    return 2*x/(xmax**2)




def acceptreject():
    mylist=[]
    while len(mylist)<10000:
        x=float(numpy.random.random(1))
        u=float(2)*float(numpy.random.random(1))
        if u<pdf(x):
            mylist.append(x)
    plt.hist(mylist,bins=30,color='purple')
    plt.xlabel("Number")
    plt.ylabel("Frequency")
    plt.title("Random numbers with Acceptance/Rejection")
    plt.savefig('question 5b')
    plt.show()

acceptreject()
